name: test workflow
on: repository_dispatch
   

jobs: 
    display_hello_message: 
          runs-on: ubuntu-latest
          inputs:  
             comment:
                description: "Enter Comment"
                required: yes
                type: string
          steps:
              - name: " echo input comment"
                run: | 
                  echo "comment: ${{ inputs.comment }} "
         
             
