name: test workflow
on: 
  workflow_dispatch:
      inputs:  
         comment:
            description: "Enter Comment"
            required: true
            type: string
   

jobs: 
    display_hello_message: 
          runs-on: ubuntu-latest
          
          steps:
              - name: " echo input comment"
                run: | 
                  echo "comment: ${{ inputs.comment }} "
         
             
